sudo: required
services:
  - docker

before_install:
  - docker build -t alidesoki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alidesoki/react-test npm test -- --coverage

after_success:
  - docker build -t alidesoki/multi-client ./client
  - docker build -t alidesoki/multi-nginx ./nginx
  - docker build -t alidesoki/multi-server ./server
  - docker build -t alidesoki/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alidesoki/multi-client
  - docker push alidesoki/multi-nginx
  - docker push alidesoki/multi-server
  - docker push alidesoki/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-233342923924
  bucket_path: docker-multi
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




