sudo: required
services:
  - docker

before_install:
  - docker build -t alidesoki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alidesoki/react-test npm test

after_success:
  - docker build -t alidesoki/multi-client ./client
  - docker build -t alidesoki/multi-nginx ./nginx
  - docker build -t alidesoki/multi-worker ./worker
  - docker build -t alidesoki/multi-server ./server
  
  - echo "$docker_pass" | docker login -u "$docker_id" --password-stdin
  - docker push alidesoki/multi-client
  - docker push alidesoki/multi-nginx
  - docker push alidesoki/multi-worker
  - docker push alidesoki/multi-server

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-233342923924"
  bucket_path: "docker-multi"
  on: 
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"




